/**
 * Editrix Electron main process.
 *
 * Opens the Launcher first. When a project is selected,
 * closes the launcher and opens the editor window.
 * Manages project creation on disk and launcher config persistence.
 */
const { app, BrowserWindow, Menu, ipcMain, dialog, protocol, net } = require('electron');
const { pathToFileURL } = require('url');
const path = require('path');
const os = require('os');
const fs = require('fs');

/** @type {BrowserWindow | null} */
let launcherWindow = null;
/** @type {BrowserWindow | null} */
let mainWindow = null;

// ── Paths ───────────────────────────────────────────────

const EDITRIX_HOME = path.join(os.homedir(), '.editrix');
const LAUNCHER_CONFIG_PATH = path.join(EDITRIX_HOME, 'launcher.json');

// ── Launcher Config (project list persistence) ──────────

function ensureDir(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function loadLauncherConfig() {
  try {
    if (fs.existsSync(LAUNCHER_CONFIG_PATH)) {
      return JSON.parse(fs.readFileSync(LAUNCHER_CONFIG_PATH, 'utf-8'));
    }
  } catch (_) {
    // Corrupted config — start fresh
  }
  return { projects: [] };
}

function saveLauncherConfig(config) {
  ensureDir(EDITRIX_HOME);
  fs.writeFileSync(LAUNCHER_CONFIG_PATH, JSON.stringify(config, null, 2), 'utf-8');
}

// ── Project Creation ────────────────────────────────────

const EDITRIX_VERSION = '0.1.0';
const EDITRIX_API_VERSION = 1;

/**
 * Generate type declarations for plugin developers.
 * Written to .editrix/types/ — auto-updated on each editor open.
 */
function generatePluginTypes(projectPath) {
  const typesDir = path.join(projectPath, '.editrix', 'types');
  ensureDir(typesDir);

  fs.writeFileSync(
    path.join(typesDir, 'editrix-env.d.ts'),
    `// Generated by Editrix v${EDITRIX_VERSION} (API v${EDITRIX_API_VERSION}) — DO NOT EDIT
// This file is auto-updated when the editor opens your project.
// Plugin tsconfig.json should include this file for full API autocomplete.

/** Disposable resource pattern. */
interface IDisposable {
  dispose(): void;
}

/** Subscription store — collects disposables for bulk cleanup. */
interface DisposableStore extends IDisposable {
  add<T extends IDisposable>(disposable: T): T;
}

/** Typed event subscriber (renamed to avoid conflict with DOM Event). */
type EditrixEvent<T> = (listener: (e: T) => void) => IDisposable;

/** Branded service identifier for type-safe DI. */
interface ServiceIdentifier<T> {
  readonly _brand: T;
  readonly id: symbol;
  readonly name: string;
}

// ─── Service Registry ───────────────────────────────────

interface IServiceRegistry {
  register<T>(id: ServiceIdentifier<T>, impl: T): IDisposable;
  get<T>(id: ServiceIdentifier<T>): T;
  getOptional<T>(id: ServiceIdentifier<T>): T | undefined;
  has(id: ServiceIdentifier<unknown>): boolean;
}

// ─── Event Bus ──────────────────────────────────────────

interface IEventBus {
  emit(eventId: string, data: unknown): void;
  on(eventId: string, handler: (data: unknown) => void): IDisposable;
  once(eventId: string, handler: (data: unknown) => void): IDisposable;
  onWild(pattern: string, handler: (eventId: string, data: unknown) => void): IDisposable;
}

// ─── Plugin System ──────────────────────────────────────

interface IPluginDescriptor {
  readonly id: string;
  readonly version: string;
  readonly dependencies?: readonly string[];
  readonly activationEvents?: readonly string[];
}

interface IPluginContext {
  readonly services: IServiceRegistry;
  readonly events: IEventBus;
  readonly subscriptions: DisposableStore;
}

interface IPlugin {
  readonly descriptor: IPluginDescriptor;
  activate(context: IPluginContext): Promise<void> | void;
  deactivate?(): Promise<void> | void;
}

// ─── Widget ─────────────────────────────────────────────

interface IWidget extends IDisposable {
  readonly id: string;
  mount(container: unknown): void;
  resize(width: number, height: number): void;
  focus(): void;
  readonly hasFocus: boolean;
}

type WidgetFactory = (panelId: string) => IWidget;

// ─── Layout Service ─────────────────────────────────────

type LayoutRegion = 'left' | 'right' | 'center' | 'top' | 'bottom';

interface PanelDescriptor {
  readonly id: string;
  readonly title: string;
  readonly icon?: string;
  readonly closable?: boolean;
  readonly defaultRegion?: LayoutRegion;
}

interface ILayoutService extends IDisposable {
  registerPanel(descriptor: PanelDescriptor): IDisposable;
  openPanel(panelId: string): void;
  closePanel(panelId: string): void;
  activatePanel(panelId: string): void;
  getDescriptor(panelId: string): PanelDescriptor | undefined;
  getAllDescriptors(): readonly PanelDescriptor[];
  getOpenPanelIds(): readonly string[];
  readonly onDidChangeLayout: EditrixEvent<unknown>;
  readonly onDidChangePanels: EditrixEvent<void>;
}

// ─── View Service ───────────────────────────────────────

interface IViewService extends IDisposable {
  registerFactory(panelId: string, factory: WidgetFactory): IDisposable;
  createWidget(panelId: string): IWidget;
  getWidget(panelId: string): IWidget | undefined;
  destroyWidget(panelId: string): void;
  readonly onDidChangeWidgets: EditrixEvent<string>;
}

// ─── Command Registry ───────────────────────────────────

interface Command {
  readonly id: string;
  readonly title: string;
  readonly category?: string;
  execute(...args: unknown[]): void | Promise<void>;
}

interface ICommandRegistry extends IDisposable {
  register(command: Command): IDisposable;
  execute(commandId: string, ...args: unknown[]): Promise<void>;
  getCommand(commandId: string): Command | undefined;
  getAll(): readonly Command[];
  has(commandId: string): boolean;
  readonly onDidChangeCommands: EditrixEvent<void>;
}

// ─── Selection Service ──────────────────────────────────

interface ISelectionService extends IDisposable {
  select(objectIds: readonly string[]): void;
  addToSelection(objectIds: readonly string[]): void;
  removeFromSelection(objectIds: readonly string[]): void;
  clearSelection(): void;
  getSelection(): readonly string[];
  isSelected(objectId: string): boolean;
  readonly onDidChangeSelection: EditrixEvent<readonly string[]>;
}

// ─── Settings Service ───────────────────────────────────

type SettingType = 'string' | 'number' | 'boolean' | 'enum' | 'range' | 'color';

interface SettingDescriptor {
  readonly key: string;
  readonly label: string;
  readonly type: SettingType;
  readonly defaultValue: unknown;
  readonly description?: string;
  readonly enumValues?: readonly string[];
  readonly min?: number;
  readonly max?: number;
  readonly step?: number;
}

interface SettingGroup {
  readonly id: string;
  readonly label: string;
  readonly settings: readonly SettingDescriptor[];
}

interface SettingChangeEvent {
  readonly key: string;
  readonly oldValue: unknown;
  readonly newValue: unknown;
}

interface ISettingsService extends IDisposable {
  registerGroup(group: SettingGroup): IDisposable;
  getGroups(): readonly SettingGroup[];
  get(key: string): unknown;
  set(key: string, value: unknown): void;
  reset(key: string): void;
  onDidChange(key: string, handler: (event: SettingChangeEvent) => void): IDisposable;
  readonly onDidChangeAny: EditrixEvent<SettingChangeEvent>;
}

// ─── Undo/Redo Service ──────────────────────────────────

interface UndoRedoOperation {
  readonly label: string;
  undo(): void;
  redo(): void;
}

interface IUndoRedoService extends IDisposable {
  push(operation: UndoRedoOperation): void;
  undo(): void;
  redo(): void;
  canUndo(): boolean;
  canRedo(): boolean;
  clear(): void;
  readonly onDidChangeState: EditrixEvent<unknown>;
}

// ─── Document Service ───────────────────────────────────

interface DocumentInfo {
  readonly filePath: string;
  readonly name: string;
  readonly extension: string;
  readonly dirty: boolean;
}

interface IDocumentService extends IDisposable {
  open(filePath: string): Promise<void>;
  save(filePath: string): Promise<void>;
  close(filePath: string): void;
  setActive(filePath: string | null): void;
  setDirty(filePath: string, dirty: boolean): void;
  getOpenDocuments(): readonly DocumentInfo[];
  readonly activeDocument: string | null;
  readonly onDidChangeDocuments: EditrixEvent<void>;
  readonly onDidChangeActive: EditrixEvent<string | null>;
  readonly onDidChangeDirty: EditrixEvent<{ filePath: string; dirty: boolean }>;
}

// ─── Scene Service ──────────────────────────────────────

interface SceneNode {
  readonly id: string;
  readonly name: string;
  readonly type: string;
  readonly icon?: string;
  readonly children: readonly string[];
  readonly visible: boolean;
}

interface ISceneService extends IDisposable {
  addNode(node: SceneNode, parentId?: string): void;
  removeNode(nodeId: string): void;
  getNode(nodeId: string): SceneNode | undefined;
  getRootIds(): readonly string[];
  getChildren(nodeId: string): readonly SceneNode[];
  setNodeName(nodeId: string, name: string): void;
  setNodeVisible(nodeId: string, visible: boolean): void;
  setProperty(nodeId: string, key: string, value: unknown): void;
  getProperty(nodeId: string, key: string): unknown;
  getProperties(nodeId: string): Record<string, unknown>;
  readonly onDidChangeScene: EditrixEvent<{ nodeId: string; changeType: string }>;
  readonly onDidChangeProperty: EditrixEvent<{ nodeId: string; key: string; oldValue: unknown; newValue: unknown }>;
}

// ─── File System Service ────────────────────────────────

interface FileEntry {
  readonly name: string;
  readonly path: string;
  readonly type: 'file' | 'directory';
  readonly size: number;
  readonly lastModified: string;
  readonly extension: string;
}

interface IFileSystemService extends IDisposable {
  readDir(dirPath: string): Promise<readonly FileEntry[]>;
  readFile(filePath: string): Promise<string>;
  writeFile(filePath: string, content: string): Promise<void>;
  stat(filePath: string): Promise<{ type: string; size: number; lastModified: string } | undefined>;
  exists(filePath: string): Promise<boolean>;
  mkdir(dirPath: string): Promise<void>;
  delete(targetPath: string): Promise<void>;
  rename(oldPath: string, newPath: string): Promise<void>;
  readonly onDidChangeFile: EditrixEvent<{ kind: string; path: string }>;
}

// ─── Console Service ────────────────────────────────────

interface IConsoleService {
  log(level: 'info' | 'warn' | 'error' | 'debug', message: string, source?: string): void;
  clear(): void;
}

// ─── Plugin Manager ─────────────────────────────────────

interface PluginManifest {
  readonly id: string;
  readonly name: string;
  readonly version: string;
  readonly description?: string;
}

interface PluginInfo {
  readonly manifest: PluginManifest;
  readonly state: string;
  readonly disabled: boolean;
  readonly builtin: boolean;
}

interface IPluginManager extends IDisposable {
  getAll(): readonly PluginInfo[];
  getInfo(pluginId: string): PluginInfo | undefined;
  disablePlugin(pluginId: string): Promise<void>;
  enablePlugin(pluginId: string): Promise<void>;
  uninstallPlugin(pluginId: string): Promise<void>;
  readonly onDidChangePlugin: EditrixEvent<unknown>;
  readonly onDidChangePluginList: EditrixEvent<void>;
}

// ─── Global API Bridge ──────────────────────────────────

interface EditrixAPI {
  readonly ILayoutService: ServiceIdentifier<ILayoutService>;
  readonly IViewService: ServiceIdentifier<IViewService>;
  readonly ICommandRegistry: ServiceIdentifier<ICommandRegistry>;
  readonly ISelectionService: ServiceIdentifier<ISelectionService>;
  readonly IPropertyService: ServiceIdentifier<unknown>;
  readonly ISettingsService: ServiceIdentifier<ISettingsService>;
  readonly IUndoRedoService: ServiceIdentifier<IUndoRedoService>;
  readonly IDocumentService: ServiceIdentifier<IDocumentService>;
  readonly IFileSystemService: ServiceIdentifier<IFileSystemService>;
  readonly ISceneService: ServiceIdentifier<ISceneService>;
  readonly IPluginManager: ServiceIdentifier<IPluginManager>;
  readonly IConsoleService: ServiceIdentifier<IConsoleService>;
}

interface Window {
  __editrix: EditrixAPI;
}
`,
    'utf-8',
  );
}

function createProjectOnDisk(projectPath, projectConfig) {
  ensureDir(projectPath);
  ensureDir(path.join(projectPath, '.editrix'));
  ensureDir(path.join(projectPath, 'assets'));
  ensureDir(path.join(projectPath, 'scenes'));

  // Write editrix.json
  fs.writeFileSync(
    path.join(projectPath, 'editrix.json'),
    JSON.stringify(projectConfig, null, 2),
    'utf-8',
  );

  // Write .editrix/settings.json (empty user overrides)
  fs.writeFileSync(
    path.join(projectPath, '.editrix', 'settings.json'),
    JSON.stringify({}, null, 2),
    'utf-8',
  );

  // Write .gitignore
  fs.writeFileSync(
    path.join(projectPath, '.gitignore'),
    [
      '.editrix/settings.json',
      '.editrix/cache/',
      '.editrix/types/',
      'node_modules/',
      '',
    ].join('\n'),
    'utf-8',
  );

  // Generate plugin type declarations
  generatePluginTypes(projectPath);

  // Write a default scene file with proper format
  fs.writeFileSync(
    path.join(projectPath, 'scenes', 'main.scene.json'),
    JSON.stringify({
      $type: 'editrix:scene',
      $version: 1,
      name: 'Main Scene',
      nodeTypes: [
        {
          type: 'gameobject',
          label: 'Game Object',
          properties: [
            { key: 'position.x', label: 'Position X', type: 'number', defaultValue: 0, group: 'Transform' },
            { key: 'position.y', label: 'Position Y', type: 'number', defaultValue: 0, group: 'Transform' },
            { key: 'position.z', label: 'Position Z', type: 'number', defaultValue: 0, group: 'Transform' },
            { key: 'rotation.x', label: 'Rotation X', type: 'range', defaultValue: 0, min: 0, max: 360, step: 1, group: 'Transform' },
            { key: 'rotation.y', label: 'Rotation Y', type: 'range', defaultValue: 0, min: 0, max: 360, step: 1, group: 'Transform' },
            { key: 'rotation.z', label: 'Rotation Z', type: 'range', defaultValue: 0, min: 0, max: 360, step: 1, group: 'Transform' },
            { key: 'active', label: 'Active', type: 'boolean', defaultValue: true, group: 'General' },
          ],
        },
      ],
      nodes: [
        { id: 'root', name: 'Root', type: 'gameobject', icon: 'layers', visible: true, properties: {} },
      ],
    }, null, 2),
    'utf-8',
  );

  // Add to launcher config
  const config = loadLauncherConfig();
  // Remove existing entry for same path if any
  config.projects = config.projects.filter((p) => p.path !== projectPath);
  config.projects.unshift({
    path: projectPath,
    name: projectConfig.name,
    editrixVersion: projectConfig.editrix,
    lastOpened: new Date().toISOString(),
    starred: false,
  });
  saveLauncherConfig(config);
}

// ── Window Creation ─────────────────────────────────────

function createLauncherWindow() {
  launcherWindow = new BrowserWindow({
    width: 960,
    height: 640,
    minWidth: 700,
    minHeight: 500,
    title: 'Editrix Launcher',
    backgroundColor: '#1b1b1f',
    frame: false,
    webPreferences: {
      contextIsolation: true,
      nodeIntegration: false,
      preload: path.join(__dirname, 'preload.cjs'),
    },
  });

  launcherWindow.loadFile(path.join(__dirname, 'launcher.html'));

  launcherWindow.on('closed', () => {
    launcherWindow = null;
  });
}

function createEditorWindow() {
  mainWindow = new BrowserWindow({
    width: 1280,
    height: 800,
    minWidth: 800,
    minHeight: 600,
    title: 'Editrix',
    backgroundColor: '#1b1b1f',
    frame: false,
    webPreferences: {
      contextIsolation: true,
      nodeIntegration: false,
      preload: path.join(__dirname, 'preload.cjs'),
    },
  });

  mainWindow.loadFile(path.join(__dirname, 'index.html'));

  mainWindow.on('closed', () => {
    mainWindow = null;
  });
}

// ── IPC: Window Controls ────────────────────────────────

ipcMain.on('window-minimize', (e) => {
  BrowserWindow.fromWebContents(e.sender)?.minimize();
});

ipcMain.on('window-maximize', (e) => {
  const win = BrowserWindow.fromWebContents(e.sender);
  if (win?.isMaximized()) {
    win.unmaximize();
  } else {
    win?.maximize();
  }
});

ipcMain.on('window-close', (e) => {
  BrowserWindow.fromWebContents(e.sender)?.close();
});

// ── IPC: System ─────────────────────────────────────────

ipcMain.on('get-home-path', (e) => {
  e.returnValue = os.homedir();
});

ipcMain.handle('select-folder', async (e) => {
  const win = BrowserWindow.fromWebContents(e.sender);
  const result = await dialog.showOpenDialog(win, {
    properties: ['openDirectory'],
    title: 'Select Project Location',
  });
  if (result.canceled || result.filePaths.length === 0) return null;
  return result.filePaths[0];
});

// ── IPC: Project Management ─────────────────────────────

ipcMain.handle('list-projects', () => {
  return loadLauncherConfig().projects;
});

ipcMain.handle('create-project', (_e, { projectPath, projectConfig }) => {
  try {
    createProjectOnDisk(projectPath, projectConfig);
    return { success: true };
  } catch (err) {
    return { success: false, error: String(err) };
  }
});

ipcMain.handle('toggle-star', (_e, projectPath) => {
  const config = loadLauncherConfig();
  const entry = config.projects.find((p) => p.path === projectPath);
  if (entry) {
    entry.starred = !entry.starred;
    saveLauncherConfig(config);
    return entry.starred;
  }
  return false;
});

ipcMain.handle('update-last-opened', (_e, projectPath) => {
  const config = loadLauncherConfig();
  const entry = config.projects.find((p) => p.path === projectPath);
  if (entry) {
    entry.lastOpened = new Date().toISOString();
    saveLauncherConfig(config);
  }
});

/** Currently open project path. */
let currentProjectPath = null;

ipcMain.on('get-project-path', (e) => {
  e.returnValue = currentProjectPath;
});

ipcMain.handle('create-plugin', async (_e, { projectPath: projPath, pluginId, pluginName }) => {
  try {
    const className = pluginName.replace(/[^a-zA-Z0-9]/g, '');
    const pluginDir = path.join(projPath, 'plugins', pluginId);
    ensureDir(pluginDir);
    ensureDir(path.join(pluginDir, 'src'));
    ensureDir(path.join(pluginDir, 'dist'));

    // plugin.json — editor reads this
    fs.writeFileSync(
      path.join(pluginDir, 'plugin.json'),
      JSON.stringify({
        id: pluginId,
        name: pluginName,
        version: '1.0.0',
        main: 'dist/index.js',
        source: 'src/index.ts',
        description: `${pluginName} plugin`,
        dependencies: ['editrix.layout', 'editrix.view', 'editrix.commands'],
        editrix: `>=${EDITRIX_VERSION}`,
        apiVersion: EDITRIX_API_VERSION,
      }, null, 2),
      'utf-8',
    );

    // package.json — developer uses this
    fs.writeFileSync(
      path.join(pluginDir, 'package.json'),
      JSON.stringify({
        name: pluginId,
        private: true,
        version: '1.0.0',
        type: 'module',
        scripts: {
          build: 'esbuild src/index.ts --bundle --outfile=dist/index.js --format=esm --platform=browser --target=es2022 --external:@editrix/*',
          watch: 'esbuild src/index.ts --bundle --outfile=dist/index.js --format=esm --platform=browser --target=es2022 --external:@editrix/* --watch',
        },
        devDependencies: {
          esbuild: '^0.27.0',
        },
      }, null, 2),
      'utf-8',
    );

    // tsconfig.json — IDE type checking, references project-level .d.ts
    fs.writeFileSync(
      path.join(pluginDir, 'tsconfig.json'),
      JSON.stringify({
        compilerOptions: {
          target: 'ES2022',
          module: 'ESNext',
          moduleResolution: 'bundler',
          strict: true,
          esModuleInterop: true,
          outDir: 'dist',
          rootDir: 'src',
          declaration: false,
        },
        include: ['src', '../../.editrix/types'],
      }, null, 2),
      'utf-8',
    );

    // src/index.ts — TypeScript source (developer edits this)
    fs.writeFileSync(
      path.join(pluginDir, 'src', 'index.ts'),
      `/**
 * ${pluginName} — Editrix plugin.
 *
 * Available services via window.__editrix:
 *   ILayoutService, IViewService, ISelectionService, IPropertyService,
 *   IDocumentService, IFileSystemService, ICommandRegistry, ISettingsService,
 *   IUndoRedoService, ISceneService, IPluginManager, IConsoleService
 */

class ${className}Widget implements IWidget {
  readonly id: string;
  private _hasFocus = false;
  private _el: HTMLDivElement | undefined;

  constructor(id: string) { this.id = id; }

  mount(container: unknown): void {
    const parent = container as HTMLElement;
    this._el = document.createElement('div');
    this._el.style.cssText = \`
      display: flex; align-items: center; justify-content: center;
      width: 100%; height: 100%;
      color: var(--editrix-text-dim); font-size: 14px;
    \`;
    this._el.textContent = '${pluginName} Panel';
    parent.appendChild(this._el);
  }

  resize(): void {}
  focus(): void { this._hasFocus = true; }
  get hasFocus(): boolean { return this._hasFocus; }
  dispose(): void { this._el?.remove(); }
}

const plugin: IPlugin = {
  descriptor: {
    id: '${pluginId}',
    version: '1.0.0',
    dependencies: ['editrix.layout', 'editrix.view'],
  },
  activate(ctx: IPluginContext) {
    const { ILayoutService, IViewService, ICommandRegistry } = window.__editrix;
    const layout = ctx.services.get(ILayoutService);
    const view = ctx.services.get(IViewService);
    const commands = ctx.services.get(ICommandRegistry);

    ctx.subscriptions.add(
      layout.registerPanel({
        id: '${pluginId}',
        title: '${pluginName}',
        defaultRegion: 'center',
        closable: true,
      }),
    );
    ctx.subscriptions.add(
      view.registerFactory('${pluginId}', (id: string) => new ${className}Widget(id)),
    );

    // Register a command so the panel can be reopened from Command Palette
    ctx.subscriptions.add(
      commands.register({
        id: '${pluginId}.show',
        title: 'Show ${pluginName}',
        category: 'Plugins',
        execute() { layout.openPanel('${pluginId}'); },
      }),
    );

    layout.openPanel('${pluginId}');
  },
};

export default plugin;
`,
      'utf-8',
    );

    // dist/index.js — initial compiled output (so it works immediately)
    // Subsequent builds are done by the developer via npm run build
    fs.writeFileSync(
      path.join(pluginDir, 'dist', 'index.js'),
      `const { ILayoutService, IViewService, ICommandRegistry } = window.__editrix;
const plugin = {
  descriptor: { id: '${pluginId}', version: '1.0.0', dependencies: ['editrix.layout', 'editrix.view', 'editrix.commands'] },
  activate(ctx) {
    const layout = ctx.services.get(ILayoutService);
    const view = ctx.services.get(IViewService);
    const commands = ctx.services.get(ICommandRegistry);
    const widget = {
      id: '${pluginId}-widget', _hasFocus: false,
      mount(c) { const el = document.createElement('div'); el.style.cssText = 'display:flex;align-items:center;justify-content:center;width:100%;height:100%;color:var(--editrix-text-dim);font-size:14px;'; el.textContent = '${pluginName} Panel'; c.appendChild(el); this._el = el; },
      resize() {}, focus() { this._hasFocus = true; }, get hasFocus() { return this._hasFocus; }, dispose() { if (this._el) this._el.remove(); },
    };
    ctx.subscriptions.add(layout.registerPanel({ id: '${pluginId}', title: '${pluginName}', defaultRegion: 'center', closable: true }));
    ctx.subscriptions.add(view.registerFactory('${pluginId}', () => widget));
    ctx.subscriptions.add(commands.register({ id: '${pluginId}.show', title: 'Show ${pluginName}', category: 'Plugins', execute() { layout.openPanel('${pluginId}'); } }));
    layout.openPanel('${pluginId}');
  },
};
export default plugin;
`,
      'utf-8',
    );

    return { success: true };
  } catch (err) {
    return { success: false, error: String(err) };
  }
});

ipcMain.on('open-project', (_e, projectPath) => {
  currentProjectPath = projectPath || null;

  // Auto-update plugin type declarations on every project open
  if (projectPath) {
    generatePluginTypes(projectPath);
  }

  // Update last opened time
  if (projectPath) {
    const config = loadLauncherConfig();
    const entry = config.projects.find((p) => p.path === projectPath);
    if (entry) {
      entry.lastOpened = new Date().toISOString();
      saveLauncherConfig(config);
    }
  }

  if (launcherWindow) {
    launcherWindow.close();
    launcherWindow = null;
  }
  if (!mainWindow) {
    createEditorWindow();
  }
});

// ── IPC: Filesystem ─────────────────────────────────────

/**
 * Normalize a path to forward slashes for cross-platform consistency.
 */
function normalizeFsPath(p) {
  return p.replace(/\\/g, '/');
}

/**
 * Build a FileEntry object from a path and fs.Stats.
 */
function toFileEntry(dirPath, name, stats) {
  const fullPath = path.join(dirPath, name);
  const ext = path.extname(name).toLowerCase();
  return {
    name,
    path: normalizeFsPath(fullPath),
    type: stats.isDirectory() ? 'directory' : 'file',
    size: stats.isDirectory() ? 0 : stats.size,
    lastModified: stats.mtime.toISOString(),
    extension: stats.isDirectory() ? '' : ext,
  };
}

ipcMain.handle('fs:readDir', async (_e, dirPath) => {
  try {
    const entries = fs.readdirSync(dirPath, { withFileTypes: true });
    const result = [];
    for (const entry of entries) {
      // Skip hidden files/dirs (starting with .)
      if (entry.name.startsWith('.')) continue;
      try {
        const stats = fs.statSync(path.join(dirPath, entry.name));
        result.push(toFileEntry(dirPath, entry.name, stats));
      } catch (_) {
        // Skip entries we can't stat (permission errors etc.)
      }
    }
    // Sort: directories first, then alphabetical
    result.sort((a, b) => {
      if (a.type !== b.type) return a.type === 'directory' ? -1 : 1;
      return a.name.localeCompare(b.name);
    });
    return result;
  } catch (err) {
    return [];
  }
});

ipcMain.handle('fs:readFile', async (_e, filePath) => {
  try {
    return fs.readFileSync(filePath, 'utf-8');
  } catch (err) {
    throw new Error(`Cannot read file: ${filePath}`);
  }
});

ipcMain.handle('fs:writeFile', async (_e, filePath, content) => {
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.writeFileSync(filePath, content, 'utf-8');
});

ipcMain.handle('fs:stat', async (_e, filePath) => {
  try {
    const stats = fs.statSync(filePath);
    return {
      type: stats.isDirectory() ? 'directory' : 'file',
      size: stats.size,
      lastModified: stats.mtime.toISOString(),
      createdAt: stats.birthtime.toISOString(),
    };
  } catch (_) {
    return null;
  }
});

ipcMain.handle('fs:exists', async (_e, filePath) => {
  return fs.existsSync(filePath);
});

ipcMain.handle('fs:mkdir', async (_e, dirPath) => {
  fs.mkdirSync(dirPath, { recursive: true });
});

ipcMain.handle('fs:delete', async (_e, targetPath) => {
  fs.rmSync(targetPath, { recursive: true, force: true });
});

ipcMain.handle('fs:rename', async (_e, oldPath, newPath) => {
  fs.renameSync(oldPath, newPath);
});

ipcMain.handle('fs:copy', async (_e, srcPath, destPath) => {
  fs.cpSync(srcPath, destPath, { recursive: true });
});

// File watcher — tracks watched directories per window
const watchers = new Map();

ipcMain.handle('fs:watch', (e, dirPath) => {
  const watchId = `${e.sender.id}:${dirPath}`;
  if (watchers.has(watchId)) return watchId;

  try {
    const watcher = fs.watch(dirPath, { recursive: true }, (eventType, filename) => {
      if (!filename) return;
      const fullPath = normalizeFsPath(path.join(dirPath, filename));
      const kind = eventType === 'rename'
        ? (fs.existsSync(path.join(dirPath, filename)) ? 'created' : 'deleted')
        : 'modified';
      // Send change event to the renderer that requested the watch
      try {
        e.sender.send('fs:change', { kind, path: fullPath });
      } catch (_) {
        // Window may have been closed
      }
    });
    watchers.set(watchId, watcher);
    return watchId;
  } catch (_) {
    return null;
  }
});

ipcMain.handle('fs:unwatch', (_e, watchId) => {
  const watcher = watchers.get(watchId);
  if (watcher) {
    watcher.close();
    watchers.delete(watchId);
  }
});

// ── Custom Protocol for WASM assets ────────────────────

protocol.registerSchemesAsPrivileged([{
  scheme: 'estella',
  privileges: { secure: true, supportFetchAPI: true, corsEnabled: true },
}]);

// ── App Lifecycle ───────────────────────────────────────

app.whenReady().then(() => {
  // Serve files from the wasm/ directory via estella:// protocol
  protocol.handle('estella', (request) => {
    // URL format: estella:///esengine.js  (non-standard scheme, no host)
    // Strip scheme prefix to get the filename
    const filename = request.url.replace(/^estella:\/\/\/?/, '');
    const filePath = path.join(__dirname, '..', 'wasm', decodeURIComponent(filename));
    const fileUrl = pathToFileURL(filePath).href;
    console.log('[estella-protocol]', request.url, '->', fileUrl);
    return net.fetch(fileUrl);
  });

  Menu.setApplicationMenu(null);
  ensureDir(EDITRIX_HOME);
  createLauncherWindow();
});

app.on('window-all-closed', () => {
  app.quit();
});

app.on('activate', () => {
  if (!launcherWindow && !mainWindow) {
    createLauncherWindow();
  }
});
