import { createServiceId, type IDisposable, Emitter, type Event } from '@editrix/common';

/**
 * Minimal type for the Emscripten-generated WASM module.
 * Full type lives in estella SDK — here we only declare what the service needs.
 */
/** Emscripten vector<string> wrapper */
export interface VectorString {
    size(): number;
    get(index: number): string;
    delete(): void;
}

export interface ESEngineModule {
    Registry: new () => CppRegistry;
    initRendererWithContext(contextHandle: number): boolean;
    shutdownRenderer(): void;
    renderFrame(registry: CppRegistry, width: number, height: number): void;
    GL: {
        registerContext(ctx: WebGLRenderingContext | WebGL2RenderingContext, attrs: Record<string, unknown>): number;
    };

    // Editor API (generated by EHT)
    editor_getComponentNames(): VectorString;
    editor_getComponentSchema(name: string): string;
    editor_addComponent(registry: CppRegistry, entity: number, name: string): boolean;
    editor_removeComponent(registry: CppRegistry, entity: number, name: string): boolean;
    editor_hasComponent(registry: CppRegistry, entity: number, name: string): boolean;
    editor_getComponents(registry: CppRegistry, entity: number): VectorString;
    editor_setFloat(registry: CppRegistry, entity: number, comp: string, field: string, value: number): boolean;
    editor_getFloat(registry: CppRegistry, entity: number, comp: string, field: string): number;
    editor_setInt(registry: CppRegistry, entity: number, comp: string, field: string, value: number): boolean;
    editor_getInt(registry: CppRegistry, entity: number, comp: string, field: string): number;
    editor_setBool(registry: CppRegistry, entity: number, comp: string, field: string, value: boolean): boolean;
    editor_getBool(registry: CppRegistry, entity: number, comp: string, field: string): boolean;

    [key: string]: unknown;
}

export interface CppRegistry {
    create(): number;
    destroy(entity: number): void;
    valid(entity: number): boolean;
    entityCount(): number;
    setParent(child: number, parent: number): void;
}

export type EstellaModuleName = 'physics' | 'spine' | 'particles' | 'tilemap';

export interface IEstellaService extends IDisposable {
    /** Load the core WASM module from a base path */
    loadCore(wasmBasePath: string): Promise<void>;

    /** Load an optional side module by name */
    loadModule(name: EstellaModuleName): Promise<void>;

    /** The loaded WASM module (undefined until loadCore completes) */
    readonly module: ESEngineModule | undefined;

    /** Whether the core module is loaded and ready */
    readonly isReady: boolean;

    /** Fires when the core module finishes loading */
    readonly onReady: Event<ESEngineModule>;
}

export const IEstellaService = createServiceId<IEstellaService>('IEstellaService');

export class EstellaService implements IEstellaService {
    private _module: ESEngineModule | undefined;
    private readonly _ready = new Emitter<ESEngineModule>();
    private _wasmBasePath = '';

    get module(): ESEngineModule | undefined { return this._module; }
    get isReady(): boolean { return this._module !== undefined; }
    get onReady(): Event<ESEngineModule> { return this._ready.event; }

    async loadCore(wasmBasePath: string): Promise<void> {
        if (this._module) return;

        this._wasmBasePath = wasmBasePath.endsWith('/') ? wasmBasePath : wasmBasePath + '/';

        const jsUrl = this._wasmBasePath + 'esengine.js';
        const wasmUrl = this._wasmBasePath + 'esengine.wasm';

        const factory = await this._loadScript(jsUrl);

        this._module = await factory({
            locateFile: (file: string) => {
                if (file.endsWith('.wasm')) return wasmUrl;
                return this._wasmBasePath + file;
            },
        }) as ESEngineModule;

        this._ready.fire(this._module);
    }

    async loadModule(name: EstellaModuleName): Promise<void> {
        if (!this._module) {
            throw new Error(`Cannot load module '${name}' before core is loaded`);
        }

        const fileMap: Record<EstellaModuleName, string> = {
            physics: 'physics.wasm',
            spine: 'spine42.wasm',
            particles: 'particles.wasm',
            tilemap: 'tilemap.wasm',
        };

        const file = fileMap[name];
        if (!file) throw new Error(`Unknown module: ${name}`);

        const url = this._wasmBasePath + file;
        const response = await fetch(url);
        if (!response.ok) throw new Error(`Failed to fetch ${url}: ${response.status}`);

        const buffer = await response.arrayBuffer();

        // Emscripten side module dynamic loading
        const mod = this._module as Record<string, unknown>;
        if (typeof mod['loadDynamicLibrary'] === 'function') {
            await (mod['loadDynamicLibrary'] as (data: ArrayBuffer) => Promise<void>)(buffer);
        }
    }

    private async _loadScript(url: string): Promise<(opts: Record<string, unknown>) => Promise<unknown>> {
        // Emscripten ESM output already has `export default ESEngineModule`.
        // Fetch source, import via Blob URL (avoids file:// import restrictions).
        const response = await fetch(url);
        if (!response.ok) throw new Error(`Failed to fetch ${url}: ${response.status}`);
        const source = await response.text();

        const blob = new Blob([source], { type: 'text/javascript' });
        const blobUrl = URL.createObjectURL(blob);
        try {
            // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment -- dynamic import returns any
            const mod: { default?: unknown } = await import(/* @vite-ignore */ blobUrl);
            if (typeof mod.default !== 'function') {
                throw new Error('Emscripten module did not export a default factory function');
            }
            return mod.default as (opts: Record<string, unknown>) => Promise<unknown>;
        } finally {
            URL.revokeObjectURL(blobUrl);
        }
    }

    dispose(): void {
        if (this._module) {
            try {
                this._module.shutdownRenderer();
            } catch { /* may not be initialized */ }
            this._module = undefined;
        }
        this._ready.dispose();
    }
}
